### ISSUE TITLE
Request: How to delete slash command?

### ISSUE THREAD

**Issue by neoarc** [ItzDerock/discord.js-v12-tutorial-series#9]
Thank you for awesome tutorial.

I've tested some and completely converted own commands.

But I've failed to find how to delete commands (it was for test purpose)

Can you help?

**Comment by devabdullahs** [comment]
u need to kick the bot 

for now that's the only solution 

until discord fix it

**Comment by ItzDerock** [comment]
kinda late reply, sorry, don't usually check github issues.
The following can be used:
`client.api.applications(client.user.id).guilds("GUILD ID").commands("COMMAND ID").delete()`
